[profile.default]
src = "src"
out = "out"
libs = ["lib"]

fs_permissions = [
  { access = "read-write", path = "./deployment_record.json" },
  { access = "read-write", path = "./sp1_deployment_record.json" },
]

[lint]
exclude_lints = ["unwrapped-modifier-logic"]